<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = \App\Models\User::first();
        if (!$user) return;

        DB::table('cliente')->insert([
            [
                'nombres_cliente' => 'Eliseo Antonio',
                'apellidos_cliente' => 'Santos Diaz',
                'dui_cliente' => '06448993-1',
                'telefono_cliente' => '7879-0673',
                'email_cliente'=> 'Eliseo@gmail.com',
                'barrio'=> 'Cuscatlán',
                'monto_max' => 1000.00,
                'id_clasificacion' => 3,
                'id_departamento' => 1,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Edras',
                'apellidos_cliente' => 'Lazo',
                'dui_cliente' => '06448993-2',
                'telefono_cliente' => '7879-0673',
                'email_cliente'=> 'Edras@gmail.com',
                'barrio'=> 'Cuscatlán',
                'monto_max' => 1000.00,
                'id_clasificacion' => 3,
                'id_departamento' => 1,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'María José',
                'apellidos_cliente' => 'Gómez Álvarez',
                'dui_cliente' => '05412345-7',
                'telefono_cliente' => '7200-1122',
                'email_cliente'=> 'maria.gomez@example.com',
                'barrio'=> 'San Benito',
                'monto_max' => 850.00,
                'id_clasificacion' => 2,
                'id_departamento' => 2,
                'id_municipio' => 5,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Carlos Andrés',
                'apellidos_cliente' => 'Mejía Pérez',
                'dui_cliente' => '06123456-3',
                'telefono_cliente' => '7312-4455',
                'email_cliente'=> 'carlos.mejia@example.com',
                'barrio'=> 'Escalón',
                'monto_max' => 1200.00,
                'id_clasificacion' => 1,
                'id_departamento' => 3,
                'id_municipio' => 7,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Ana Fernanda',
                'apellidos_cliente' => 'Rivas López',
                'dui_cliente' => '07234567-8',
                'telefono_cliente' => '7688-9900',
                'email_cliente'=> 'ana.rivas@example.com',
                'barrio'=> 'Santa Anita',
                'monto_max' => 950.00,
                'id_clasificacion' => 2,
                'id_departamento' => 4,
                'id_municipio' => 9,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Luis Fernando',
                'apellidos_cliente' => 'Herrera Meléndez',
                'dui_cliente' => '01234567-9',
                'telefono_cliente' => '7123-4567',
                'email_cliente'=> 'luis.herrera@gmail.com',
                'barrio'=> 'El Centro, San Miguel',
                'monto_max' => 1500.00,
                'id_clasificacion' => 1, // Frecuente
                'id_departamento' => 12,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Gabriela Nohemy',
                'apellidos_cliente' => 'Quintanilla Rosa',
                'dui_cliente' => '03456789-0',
                'telefono_cliente' => '7980-1234',
                'email_cliente'=> 'gaby.quintanilla@live.com',
                'barrio'=> 'El Calvario, Santa Tecla',
                'monto_max' => 500.00,
                'id_clasificacion' => 2, // Moroso
                'id_departamento' => 4,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Roberto Carlos',
                'apellidos_cliente' => 'Lemus Orellana',
                'dui_cliente' => '08765432-1',
                'telefono_cliente' => '7055-6677',
                'email_cliente'=> 'roberto.lemus@outlook.com',
                'barrio'=> 'El Angel, Sonsonate',
                'monto_max' => 2000.00,
                'id_clasificacion' => 3, // Nuevo
                'id_departamento' => 3,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Katherine Michelle',
                'apellidos_cliente' => 'Flores Vega',
                'dui_cliente' => '02345678-4',
                'telefono_cliente' => '7544-3322',
                'email_cliente'=> 'katy.flores@gmail.com',
                'barrio'=> 'San Rafael, Santa Ana',
                'monto_max' => 1100.00,
                'id_clasificacion' => 1,
                'id_departamento' => 2,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Josué David',
                'apellidos_cliente' => 'Martínez Sosa',
                'dui_cliente' => '04567890-5',
                'telefono_cliente' => '7233-1100',
                'email_cliente'=> 'josue.martinez@gmail.com',
                'barrio'=> 'Las Flores, Ahuachapán',
                'monto_max' => 750.00,
                'id_clasificacion' => 3,
                'id_departamento' => 1,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Patricia Elena',
                'apellidos_cliente' => 'Benítez Guzmán',
                'dui_cliente' => '09876543-2',
                'telefono_cliente' => '7100-2233',
                'email_cliente'=> 'paty.benitez@yahoo.com',
                'barrio'=> 'San Sebastian, La Unión',
                'monto_max' => 900.00,
                'id_clasificacion' => 2,
                'id_departamento' => 14,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Jorge Alberto',
                'apellidos_cliente' => 'Zelaya Ortíz',
                'dui_cliente' => '05678901-6',
                'telefono_cliente' => '7455-8899',
                'email_cliente'=> 'jorge.zelaya@gmail.com',
                'barrio'=> 'La Parroquia, Usulután',
                'monto_max' => 1300.00,
                'id_clasificacion' => 1,
                'id_departamento' => 11,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Sandra Elizabeth',
                'apellidos_cliente' => 'Valladares Meza',
                'dui_cliente' => '01122334-9',
                'telefono_cliente' => '7811-2244',
                'email_cliente'=> 'sandra.valla@gmail.com',
                'barrio'=> 'Chile Abajo, Chalatenango',
                'monto_max' => 1000.00,
                'id_clasificacion' => 3,
                'id_departamento' => 5,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Miguel Ángel',
                'apellidos_cliente' => 'Portillo Alfaro',
                'dui_cliente' => '03344556-7',
                'telefono_cliente' => '7099-0011',
                'email_cliente'=> 'miguel.portillo@gmail.com',
                'barrio'=> 'San Juan, San Vicente',
                'monto_max' => 1800.00,
                'id_clasificacion' => 1,
                'id_departamento' => 9,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres_cliente' => 'Claudia Ivette',
                'apellidos_cliente' => 'Rodríguez Peña',
                'dui_cliente' => '06677889-2',
                'telefono_cliente' => '7288-4455',
                'email_cliente'=> 'claudia.rodriguez@gmail.com',
                'barrio'=> 'El Centro, Sensuntepeque',
                'monto_max' => 600.00,
                'id_clasificacion' => 2,
                'id_departamento' => 7,
                'id_municipio' => 1,
                'user_id' => $user->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
